tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "vitorgalvao/tiny-scripts"
brew "annie"
brew "readline"
brew "asciinema"
brew "gettext"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bat"
brew "carthage"
brew "coreutils"
brew "cowsay"
brew "ctags"
brew "gnu-tar"
brew "dpkg"
brew "fakeroot"
brew "fish"
brew "format-udf"
brew "fortune"
brew "fswatch"
brew "fzf"
brew "jpeg"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pinentry"
brew "gnupg"
brew "go"
brew "gource"
brew "gpgme"
brew "gtk+"
brew "haxe"
brew "lua"
brew "highlight"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jasper"
brew "jq"
brew "libusb-compat"
brew "libgphoto2"
brew "libicns"
brew "libyaml"
brew "lxc"
brew "lynx"
brew "makedepend"
brew "mas"
brew "mitmproxy"
brew "mysql", restart_service: true
brew "nano"
brew "openssl@1.1"
brew "pandoc"
brew "pdf2svg"
brew "pipenv"
brew "pkg-config"
brew "potrace"
brew "pth"
brew "pypy3"
brew "qemu"
brew "redis", restart_service: true
brew "ruby"
brew "sane-backends"
brew "sdl2_ttf"
brew "the_silver_searcher"
brew "unar"
brew "vcsh"
brew "wine"
brew "yarn"
brew "zlib"
brew "heroku/brew/heroku"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "0xed"
cask "atom"
cask "betterzip"
cask "blender"
cask "blockblock"
cask "do-not-disturb"
cask "flux"
cask "font-fira-code"
cask "github"
cask "hyper"
cask "karabiner-elements"
cask "kextviewr"
cask "keybase"
cask "knockknock"
cask "mojibar"
cask "now"
cask "oversight"
cask "powershell"
cask "provisionql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "racket"
cask "ransomwhere"
cask "reikey"
cask "suspicious-package"
cask "uxprotect"
cask "webpquicklook"
cask "whatsyoursign"
cask "xquartz"
mas "AdBlock", id: 1402042596
mas "Caffeinated", id: 1362171212
mas "Cascadea", id: 1432182561
mas "GarageBand", id: 682658836
mas "GhosteryLite", id: 1436953057
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Memory Diag", id: 748212890
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PCalc", id: 403504866
mas "Reeder", id: 1449412482
mas "Slack", id: 803453959
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
